In [21]:
import math
import numpy as np

u = np.array((1, 2, 3, 4))
v1 = np.zeros(4)    #(1, 4): index 1 is out of bounds for axis 0 with size 1
for i in range(4):
    v1[i] = math.exp(u[i])
print("v1(shape:" + str(np.shape(v1)) + "): " + str(v1))

# same as above
u = np.array([[1, 2, 3, 4],])
v1 = np.zeros((1, 4))
for i in range(4):
    v1[0, i] = math.exp(u[0, i])
print("v1(shape:" + str(np.shape(v1)) + "): " + str(v1))

v2 = np.exp(u)
# v2 = np.log(u)
# v2 = np.log10(u)
# v2 = np.abs(u)
# v2 = np.maximum(u, 3)
print("v2(shape:" + str(np.shape(v2)) + "): " + str(v2))

v1(shape:(4,)): [ 2.71828183  7.3890561  20.08553692 54.59815003]
v1(shape:(1, 4)): [[ 2.71828183  7.3890561  20.08553692 54.59815003]]
v2(shape:(1, 4)): [[ 2.71828183  7.3890561  20.08553692 54.59815003]]


In [1]:
import numpy as np
A = np.array([[1, 2], [8, 6], [3, 4]])
A[0:3:1, :]

array([[1, 2],
       [8, 6],
       [3, 4]])

In [6]:
import numpy as np
b = np.array([
    [[1, 2, 3], [11, 12, 13], [21, 22, 23]], 
    [[31, 32, 33], [41, 42, 43], [51, 52, 53]], 
    [[6, 62, 63], [71, 72, 73], [81, 82, 83]], 
    ])
b[:, 1, 1]

array([12, 42, 72])

In [12]:
import numpy as np

a = np.zeros([5, 1])
b = np.ones([2, 2], dtype='int32')
c = np.full([2, 2], 3)
c

array([[3, 3],
       [3, 3]])

In [11]:
print(np.random.rand(2, 3))
print(np.random.randint(5))
print(np.random.randint(4, 10, size=(2, 3)))

[[0.97984112 0.38493618 0.61624832]
 [0.79641969 0.93773967 0.32595654]]
2
[[5 4 9]
 [7 4 5]]


In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
o = np.ones((5, 5))
z = np.zeros((3, 3))
z[1, 1] = 9
print(z)
o[1:-1, 1:-1] = z
print(o)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
