In [4]:
import numpy as np

A = np.random.randn(5)
print(type(A))
print(A.shape)
print(A)

<class 'numpy.ndarray'>
(5,)
[ 1.53850371 -1.59992441 -1.02190734 -1.35083085 -0.47070214]


In [6]:
print(A.T)
print(np.dot(A, A.T))

[ 1.53850371 -1.59992441 -1.02190734 -1.35083085 -0.47070214]
8.017350885600539


In [9]:
B = np.random.randn(5, 1)
print(type(B))
print(B.shape)
print(B)

<class 'numpy.ndarray'>
(5, 1)
[[-0.79195408]
 [-0.12904506]
 [-0.07413626]
 [-1.19284041]
 [ 0.69548787]]


In [10]:
print(B.T)

[[-0.79195408 -0.12904506 -0.07413626 -1.19284041  0.69548787]]


In [11]:
print(np.dot(B, B.T))

[[ 0.62719127  0.10219776  0.05871252  0.94467483 -0.55079446]
 [ 0.10219776  0.01665263  0.00956692  0.15393017 -0.08974928]
 [ 0.05871252  0.00956692  0.00549619  0.08843273 -0.05156087]
 [ 0.94467483  0.15393017  0.08843273  1.42286825 -0.82960604]
 [-0.55079446 -0.08974928 -0.05156087 -0.82960604  0.48370338]]
